/*
 * Copyright (C) 2014 Hande Özaygen
 *
 * This file is part of dpgame.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>
 */
package org.dpgame.puzzle.controller;

import java.util.ArrayList;

import org.dpgame.puzzle.model.IPuzzleGeneratorBuilder;
import org.dpgame.puzzle.model.components.ISolutionPart;

public interface IPuzzleManager {

	public abstract void setSelectedPuzzle(IPuzzleGeneratorBuilder puzzleGeneratorBuilder, String puzzleType, int level);

	/**
	 * Generates a new puzzle of the current level using puzzle manager and
	 * displays it.
	 */
	public abstract void constructNewPuzzle();

	public abstract void viewMenu();

	public abstract void viewHelp(String url);

	/**
	 * Runs the solution generated by the player. If the solution solves the
	 * puzzle, a new puzzle with the same level is generated. If solution does
	 * not solve the puzzle, displays the current puzzle in its initial form.
	 */
	public abstract void run(ArrayList<ISolutionPart> solutionParts);

}