/*
 * Copyright (C) 2014 Hande Özaygen
 *
 * This file is part of dpgame.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>
 */
package org.dpgame.puzzle.model;

/**
 * A puzzle builder.
 * <p>
 * A puzzle is basically composed of a board, objects on the board, a toolbox
 * that contains tools to solve the puzzle, a solution builder which applies the
 * specified solution by the player to the tools in the toolbox, a solver that
 * executes the solution generated by solution builder.
 * <p>
 * Puzzle builder generates random puzzles depending on the level information specified.
 * <p>
 * Puzzle builder generates help and hint for the puzzle.
 * 
 * @see IPuzzle
 * 
 * @author Hande Özaygen
 * @version 1.1.0
 * 
 */
public interface IPuzzleGeneratorBuilder {

	/**
	 * Builds the board of the puzzle.
	 */
	public void buildBoardParameters();

	/**
	 * Builds the solution builder that will generate the solution for the
	 * puzzle.
	 */
	public void buildActionList();

	/**
	 * Builds the toolbox of the puzzle.
	 */
	public void buildToolboxParameters();

	/**
	 * Builds the board objects to be located on the board.
	 */
	public void buildBoardObjects();

//	/**
//	 * Builds the hint for the generated puzzle.
//	 */
//	public void buildHint();
//
//	/**
//	 * Builds the help of the puzzle.
//	 */
//	public void buildHelp();

	/**
	 * Getter method for the puzzle.
	 * 
	 * @return the puzzle.
	 */
	public IPuzzleGenerator getPuzzleGenerator();
}
